name: Setup Frontend
description: Setup Node.js and pnpm for frontend

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '20'
  pnpm-version:
    description: pnpm version to use
    required: false
    default: '8'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: frontend/pnpm-lock.yaml

    - shell: bash
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile
