name: Update Dependencies
description: Update dependencies for a service

inputs:
  service:
    description: Service name (backend or frontend)
    required: true
  working-directory:
    description: Working directory
    required: true

runs:
  using: composite
  steps:
    - if: inputs.service == 'frontend'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pnpm update --latest --interactive=false
        pnpm dedupe
